import { useState } from "react";
import EmptyState from "./EmptyState";
import {
  FileText, Download, ChevronDown, Target, ListChecks, Lightbulb,
  AlertTriangle, TrendingUp, BookMarked, ExternalLink, FileType,
} from "lucide-react";

function downloadBlob(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function buildWordHtml(report) {
  const findingsHtml = report.findings
    .map((f) => `<p><b>[${f.tag.toUpperCase()}]</b> ${f.text}</p>`)
    .join("");
  return `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
  <head><meta charset="utf-8"><title>${report.title}</title></head>
  <body style="font-family:Calibri,Arial,sans-serif;">
    <h1>${report.title}</h1>
    <h2>Executive Summary</h2><p>${report.executive_summary}</p>
    <h2>Research Objective</h2><p>${report.research_objective}</p>
    <h2>Methodology</h2><p>${report.methodology}</p>
    <h2>Key Findings</h2>${findingsHtml}
    <h2>Risks and Limitations</h2><p>${report.risks_and_limitations}</p>
    <h2>Recommendation</h2><p>${report.recommendation}</p>
    <h2>Evidence and References</h2><p>${report.evidence_references.join(", ")}</p>
  </body></html>`;
}

export default function ReportView({ reportData }) {
  const [exportOpen, setExportOpen] = useState(false);

  if (!reportData || !reportData.available) {
    return <EmptyState icon={FileText} title="No final report yet" body="The Writer agent produces this once the Critic approves (or the revision cap is reached)." />;
  }

  const report = reportData.report;
  const safeName = report.title.slice(0, 40).replace(/[^a-z0-9]+/gi, "_");

  const handleExport = (type) => {
    setExportOpen(false);
    if (type === "markdown") downloadBlob(reportData.markdown, `${safeName}.md`, "text/markdown");
    if (type === "word") downloadBlob(buildWordHtml(report), `${safeName}.doc`, "application/msword");
    if (type === "pdf") window.print();
  };

  return (
    <div className="report-doc">
      <div className="report-header">
        <div>
          <h1 className="report-title">{report.title}</h1>
          <div className="report-meta">Generated by MARDI Multi-Agent Platform</div>
        </div>
        <div className="export-menu">
          <button className="btn btn-primary" onClick={() => setExportOpen(!exportOpen)}>
            <Download size={14} /> Export <ChevronDown size={13} />
          </button>
          {exportOpen && (
            <div className="export-dropdown">
              <button onClick={() => handleExport("markdown")}><FileText size={14} /> Markdown (.md)</button>
              <button onClick={() => handleExport("pdf")}><FileType size={14} /> PDF (print dialog)</button>
              <button onClick={() => handleExport("word")}><BookMarked size={14} /> Word (.doc)</button>
            </div>
          )}
        </div>
      </div>

      <div className="report-section">
        <div className="section-heading"><Target size={13} /> Executive Summary</div>
        <p>{report.executive_summary}</p>
      </div>
      <div className="report-section">
        <div className="section-heading"><Target size={13} /> Research Objective</div>
        <p>{report.research_objective}</p>
      </div>
      <div className="report-section">
        <div className="section-heading"><ListChecks size={13} /> Methodology</div>
        <p>{report.methodology}</p>
      </div>
      <div className="report-section">
        <div className="section-heading"><Lightbulb size={13} /> Key Findings</div>
        {report.findings.map((f, i) => (
          <div className="finding-item" key={i}>
            <span className={`finding-tag ${f.tag}`}>{f.tag}</span>
            <span style={{ color: "var(--text-dim)", fontSize: 13.5 }}>{f.text}</span>
          </div>
        ))}
      </div>
      <div className="report-section">
        <div className="section-heading"><AlertTriangle size={13} /> Risks and Limitations</div>
        <div className="risk-box"><p>{report.risks_and_limitations}</p></div>
      </div>
      <div className="report-section">
        <div className="section-heading"><TrendingUp size={13} /> Recommendation</div>
        <div className="recommendation-box"><p>{report.recommendation}</p></div>
      </div>
      <div className="report-section">
        <div className="section-heading"><BookMarked size={13} /> Evidence and References</div>
        <div className="chip-row">
          {report.evidence_references.map((id) => (
            <span key={id} className="chip mono" style={{ cursor: "default", display: "inline-flex", alignItems: "center", gap: 5 }}>
              {id} <ExternalLink size={11} />
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}
